name: myenv2
dependencies:
  - numpy
  - pandas
  - scipy
  - matplotlib
  - python=3.11  # Specify the Python version you want to use
  - pip
  - openpyxl
  - python-dotenv
  - nltk
  - pip:
    - scipy
    - tenacity
    - tiktoken  # Ensure this is the correct package name, as "tiktoken" might be a typo
    - termcolor
    - openai
  - jupyter  # Jupyter Notebook package
  - nb_conda